server:
  port: 80
spring:
  jpa:
    show-sql: true     # 设置hibernate操作的时候在控制台显示其真正的sql
    hibernate:
      ddl-auto: update 
  datasource:
    #url: jdbc:h2:file:~/.h2/testdb   #spring.datasource.url = jdbc:h2:file:D:\\test\\db\\testdb
    url: jdbc:h2:file:D:\\testdb
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
